name: Go SDK CI

on:
  push:
    branches:
      - members/ignat/darwin_cmake

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        module: ["yt/go", "library/go/core/log", "library/go/x/xreflect", "library/go/blockcodecs"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Build
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go build -v -mod=readonly ./...

      - name: Run tests
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go test -v -mod=readonly ./...

      - name: Run tests with race detector
        working-directory: ${{ matrix.module }}
        shell: bash
        run: |
          go test -v -mod=readonly -race ./...
