name: Java SDK CI

on:
  push:
    branches:
      - members/ignat/darwin_cmake

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew testIntegration

      - name: Get latest Java SDK tag
        uses: oprypin/find-latest-tag@v1.1.2
        id: latest_tag
        with:
          repository: ytsaurus/ytsaurus
          regex: 'java-sdk/*'

      - name: Get snapshot release version
        id: release_version
        run: |
          LATEST_TAG=${{ steps.latest_tag.outputs.tag }}; echo "RELEASE_VERSION=$(echo ${LATEST_TAG#java-sdk/})" >> $GITHUB_OUTPUT

      - name: Publish snapshot
        run: ./gradlew publish -PossrhUsername=${{ secrets.OSSRH_USERNAME }} -PossrhPassword=${{ secrets.OSSRH_PASSWORD }} -Pversion="${{ steps.release_version.outputs.RELEASE_VERSION }}-SNAPSHOT" -PsigningPassword=${{ secrets.GPG_PASSWORD }} -PsigningKey="${{ secrets.GPG_PRIVATE_KEY }}"
